# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/data/v0/data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/data/v0/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passmanager.common.v0 import error_pb2 as passmanager_dot_common_dot_v0_dot_error__pb2
from passmanager.common.v0 import secure_pb2 as passmanager_dot_common_dot_v0_dot_secure__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1epassmanager/data/v0/data.proto\x12\x13passmanager.data.v0\x1a!passmanager/common/v0/error.proto\x1a\"passmanager/common/v0/secure.proto2\x8a\x04\n\x04\x44\x61ta\x12U\n\x06\x43reate\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12S\n\x04\x45\x64it\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12U\n\x06\x44\x65lete\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12R\n\x03Get\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12S\n\x04List\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12V\n\x06Health\x12%.passmanager.common.v0.HealthResponse\x1a%.passmanager.common.v0.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.data.v0.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=127
  _globals['_DATA']._serialized_end=649
# @@protoc_insertion_point(module_scope)
