"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EntryName(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EntryName: _TypeAlias = EntryName  # noqa: Y015

@_typing.final
class EntryData(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WEBSITE_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    NOTES_FIELD_NUMBER: _builtins.int
    website: _builtins.str
    username: _builtins.str
    password: _builtins.str
    notes: _builtins.str
    def __init__(
        self,
        *,
        website: _builtins.str | None = ...,
        username: _builtins.str | None = ...,
        password: _builtins.str | None = ...,
        notes: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_notes", b"_notes", "_password", b"_password", "_username", b"_username", "_website", b"_website", "notes", b"notes", "password", b"password", "username", b"username", "website", b"website"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_notes", b"_notes", "_password", b"_password", "_username", b"_username", "_website", b"_website", "notes", b"notes", "password", b"password", "username", b"username", "website", b"website"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__notes: _TypeAlias = _typing.Literal["notes"]  # noqa: Y015
    _WhichOneofArgType__notes: _TypeAlias = _typing.Literal["_notes", b"_notes"]  # noqa: Y015
    _WhichOneofReturnType__password: _TypeAlias = _typing.Literal["password"]  # noqa: Y015
    _WhichOneofArgType__password: _TypeAlias = _typing.Literal["_password", b"_password"]  # noqa: Y015
    _WhichOneofReturnType__username: _TypeAlias = _typing.Literal["username"]  # noqa: Y015
    _WhichOneofArgType__username: _TypeAlias = _typing.Literal["_username", b"_username"]  # noqa: Y015
    _WhichOneofReturnType__website: _TypeAlias = _typing.Literal["website"]  # noqa: Y015
    _WhichOneofArgType__website: _TypeAlias = _typing.Literal["_website", b"_website"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__notes) -> _WhichOneofReturnType__notes | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__password) -> _WhichOneofReturnType__password | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__username) -> _WhichOneofReturnType__username | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__website) -> _WhichOneofReturnType__website | None: ...

Global___EntryData: _TypeAlias = EntryData  # noqa: Y015
