# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/common/v0/entries.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/common/v0/entries.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#passmanager/common/v0/entries.proto\x12\x15passmanager.common.v0\"\x19\n\tEntryName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x93\x01\n\tEntryData\x12\x14\n\x07website\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08username\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08password\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05notes\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\n\n\x08_websiteB\x0b\n\t_usernameB\x0b\n\t_passwordB\x08\n\x06_notesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.common.v0.entries_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTRYNAME']._serialized_start=62
  _globals['_ENTRYNAME']._serialized_end=87
  _globals['_ENTRYDATA']._serialized_start=90
  _globals['_ENTRYDATA']._serialized_end=237
# @@protoc_insertion_point(module_scope)
