"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _ErrorCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ErrorCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNSPECIFIED: _ErrorCode.ValueType  # 0
    RQS00: _ErrorCode.ValueType  # 10
    RQS01: _ErrorCode.ValueType  # 11
    RQS02: _ErrorCode.ValueType  # 12
    RQS03: _ErrorCode.ValueType  # 13
    SVR00: _ErrorCode.ValueType  # 20
    SVR01: _ErrorCode.ValueType  # 21
    GNR00: _ErrorCode.ValueType  # 30
    GNR01: _ErrorCode.ValueType  # 31
    OPR00: _ErrorCode.ValueType  # 40
    OPR01: _ErrorCode.ValueType  # 41
    OPR02: _ErrorCode.ValueType  # 42

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper): ...

UNSPECIFIED: ErrorCode.ValueType  # 0
RQS00: ErrorCode.ValueType  # 10
RQS01: ErrorCode.ValueType  # 11
RQS02: ErrorCode.ValueType  # 12
RQS03: ErrorCode.ValueType  # 13
SVR00: ErrorCode.ValueType  # 20
SVR01: ErrorCode.ValueType  # 21
GNR00: ErrorCode.ValueType  # 30
GNR01: ErrorCode.ValueType  # 31
OPR00: ErrorCode.ValueType  # 40
OPR01: ErrorCode.ValueType  # 41
OPR02: ErrorCode.ValueType  # 42
Global___ErrorCode: _TypeAlias = ErrorCode  # noqa: Y015

@_typing.final
class HealthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEALTH_FIELD_NUMBER: _builtins.int
    health: _builtins.bool
    def __init__(
        self,
        *,
        health: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["health", b"health"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HealthRequest: _TypeAlias = HealthRequest  # noqa: Y015

@_typing.final
class HealthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEALTH_FIELD_NUMBER: _builtins.int
    health: _builtins.bool
    def __init__(
        self,
        *,
        health: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["health", b"health"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HealthResponse: _TypeAlias = HealthResponse  # noqa: Y015

@_typing.final
class Failure(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_LIST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error_list(self) -> _containers.RepeatedCompositeFieldContainer[Global___Error]: ...
    def __init__(
        self,
        *,
        error_list: _abc.Iterable[Global___Error] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error_list", b"error_list"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Failure: _TypeAlias = Failure  # noqa: Y015

@_typing.final
class Error(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIELD_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    field: _builtins.str
    code: Global___ErrorCode.ValueType
    description: _builtins.str
    def __init__(
        self,
        *,
        field: _builtins.str = ...,
        code: Global___ErrorCode.ValueType = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "description", b"description", "field", b"field"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015
