"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from passmanager.common.v0 import error_pb2 as _error_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SecureRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    REQUEST_NUMBER_FIELD_NUMBER: _builtins.int
    ENCRYPTED_DATA_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    request_number: _builtins.int
    encrypted_data: _builtins.bytes
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        request_number: _builtins.int = ...,
        encrypted_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encrypted_data", b"encrypted_data", "request_number", b"request_number", "session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SecureRequest: _TypeAlias = SecureRequest  # noqa: Y015

@_typing.final
class SecureResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SESSION_ID_FIELD_NUMBER: _builtins.int
        ENCRYPTED_DATA_FIELD_NUMBER: _builtins.int
        session_id: _builtins.str
        encrypted_data: _builtins.bytes
        def __init__(
            self,
            *,
            session_id: _builtins.str = ...,
            encrypted_data: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["encrypted_data", b"encrypted_data", "session_id", b"session_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    SUCCESS_DATA_FIELD_NUMBER: _builtins.int
    FAILURE_DATA_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def success_data(self) -> Global___SecureResponse.Success: ...
    @_builtins.property
    def failure_data(self) -> _error_pb2.Failure: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        success_data: Global___SecureResponse.Success | None = ...,
        failure_data: _error_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success_data", b"success_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success", b"success", "success_data", b"success_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["success_data", "failure_data"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___SecureResponse: _TypeAlias = SecureResponse  # noqa: Y015
