# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/session/v0/session_payloads.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/session/v0/session_payloads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-passmanager/session/v0/session_payloads.proto\x12\x16passmanager.session.v0\"A\n\x14SessionDeleteRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\".\n\x15SessionDeleteResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\",\n\x13SessionCleanRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\"-\n\x14SessionCleanResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.session.v0.session_payloads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONDELETEREQUEST']._serialized_start=73
  _globals['_SESSIONDELETEREQUEST']._serialized_end=138
  _globals['_SESSIONDELETERESPONSE']._serialized_start=140
  _globals['_SESSIONDELETERESPONSE']._serialized_end=186
  _globals['_SESSIONCLEANREQUEST']._serialized_start=188
  _globals['_SESSIONCLEANREQUEST']._serialized_end=232
  _globals['_SESSIONCLEANRESPONSE']._serialized_start=234
  _globals['_SESSIONCLEANRESPONSE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
