"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from passmanager.common.v0 import error_pb2 as _error_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SessionStartRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionStartRequest: _TypeAlias = SessionStartRequest  # noqa: Y015

@_typing.final
class SessionStartResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        AUTH_ID_FIELD_NUMBER: _builtins.int
        SRP_SALT_FIELD_NUMBER: _builtins.int
        EPH_PUBLIC_B_FIELD_NUMBER: _builtins.int
        MASTER_KEY_SALT_FIELD_NUMBER: _builtins.int
        auth_id: _builtins.str
        srp_salt: _builtins.bytes
        eph_public_b: _builtins.bytes
        master_key_salt: _builtins.bytes
        def __init__(
            self,
            *,
            auth_id: _builtins.str = ...,
            srp_salt: _builtins.bytes = ...,
            eph_public_b: _builtins.bytes = ...,
            master_key_salt: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_id", b"auth_id", "eph_public_b", b"eph_public_b", "master_key_salt", b"master_key_salt", "srp_salt", b"srp_salt"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    SUCCESS_DATA_FIELD_NUMBER: _builtins.int
    FAILURE_DATA_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def success_data(self) -> Global___SessionStartResponse.Success: ...
    @_builtins.property
    def failure_data(self) -> _error_pb2.Failure: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        success_data: Global___SessionStartResponse.Success | None = ...,
        failure_data: _error_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success_data", b"success_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success", b"success", "success_data", b"success_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["success_data", "failure_data"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___SessionStartResponse: _TypeAlias = SessionStartResponse  # noqa: Y015

@_typing.final
class SessionAuthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    AUTH_ID_FIELD_NUMBER: _builtins.int
    EPH_VAL_A_FIELD_NUMBER: _builtins.int
    PROOF_VAL_M1_FIELD_NUMBER: _builtins.int
    MAXIMUM_REQUESTS_FIELD_NUMBER: _builtins.int
    EXPIRY_TIME_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    auth_id: _builtins.str
    eph_val_a: _builtins.bytes
    proof_val_m1: _builtins.bytes
    maximum_requests: _builtins.int
    expiry_time: _builtins.int
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        auth_id: _builtins.str = ...,
        eph_val_a: _builtins.bytes = ...,
        proof_val_m1: _builtins.bytes = ...,
        maximum_requests: _builtins.int = ...,
        expiry_time: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_id", b"auth_id", "eph_val_a", b"eph_val_a", "expiry_time", b"expiry_time", "maximum_requests", b"maximum_requests", "proof_val_m1", b"proof_val_m1", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionAuthRequest: _TypeAlias = SessionAuthRequest  # noqa: Y015

@_typing.final
class SessionAuthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SESSION_ID_FIELD_NUMBER: _builtins.int
        SERVER_PROOF_FIELD_NUMBER: _builtins.int
        session_id: _builtins.str
        server_proof: _builtins.bytes
        def __init__(
            self,
            *,
            session_id: _builtins.str = ...,
            server_proof: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["server_proof", b"server_proof", "session_id", b"session_id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    SUCCESS_DATA_FIELD_NUMBER: _builtins.int
    FAILURE_DATA_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def success_data(self) -> Global___SessionAuthResponse.Success: ...
    @_builtins.property
    def failure_data(self) -> _error_pb2.Failure: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        success_data: Global___SessionAuthResponse.Success | None = ...,
        failure_data: _error_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success_data", b"success_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success", b"success", "success_data", b"success_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["success_data", "failure_data"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___SessionAuthResponse: _TypeAlias = SessionAuthResponse  # noqa: Y015
