"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SessionDeleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    session_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionDeleteRequest: _TypeAlias = SessionDeleteRequest  # noqa: Y015

@_typing.final
class SessionDeleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionDeleteResponse: _TypeAlias = SessionDeleteResponse  # noqa: Y015

@_typing.final
class SessionCleanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionCleanRequest: _TypeAlias = SessionCleanRequest  # noqa: Y015

@_typing.final
class SessionCleanResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SessionCleanResponse: _TypeAlias = SessionCleanResponse  # noqa: Y015
