# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/user/v0/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/user/v0/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passmanager.common.v0 import error_pb2 as passmanager_dot_common_dot_v0_dot_error__pb2
from passmanager.common.v0 import secure_pb2 as passmanager_dot_common_dot_v0_dot_secure__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1epassmanager/user/v0/user.proto\x12\x13passmanager.user.v0\x1a!passmanager/common/v0/error.proto\x1a\"passmanager/common/v0/secure.proto\"l\n\x13UserRegisterRequest\x12\x14\n\x0cnew_username\x18\x01 \x01(\x0c\x12\x10\n\x08srp_salt\x18\x02 \x01(\x0c\x12\x14\n\x0csrp_verifier\x18\x03 \x01(\x0c\x12\x17\n\x0fmaster_key_salt\x18\x04 \x01(\x0c\"\xd6\x01\n\x14UserRegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12I\n\x0csuccess_data\x18\x02 \x01(\x0b\x32\x31.passmanager.user.v0.UserRegisterResponse.SuccessH\x00\x12\x36\n\x0c\x66\x61ilure_data\x18\x03 \x01(\x0b\x32\x1e.passmanager.common.v0.FailureH\x00\x1a \n\x07Success\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x42\x08\n\x06result2\xef\x02\n\x04User\x12_\n\x08Register\x12(.passmanager.user.v0.UserRegisterRequest\x1a).passmanager.user.v0.UserRegisterResponse\x12W\n\x08Username\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12U\n\x06\x44\x65lete\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12V\n\x06Health\x12%.passmanager.common.v0.HealthResponse\x1a%.passmanager.common.v0.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.user.v0.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREGISTERREQUEST']._serialized_start=126
  _globals['_USERREGISTERREQUEST']._serialized_end=234
  _globals['_USERREGISTERRESPONSE']._serialized_start=237
  _globals['_USERREGISTERRESPONSE']._serialized_end=451
  _globals['_USERREGISTERRESPONSE_SUCCESS']._serialized_start=409
  _globals['_USERREGISTERRESPONSE_SUCCESS']._serialized_end=441
  _globals['_USER']._serialized_start=454
  _globals['_USER']._serialized_end=821
# @@protoc_insertion_point(module_scope)
