# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/data/v0/data_payloads.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/data/v0/data_payloads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'passmanager/data/v0/data_payloads.proto\x12\x13passmanager.data.v0\"R\n\x11\x44\x61taCreateRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x12\n\nentry_name\x18\x02 \x01(\x0c\x12\x12\n\nentry_data\x18\x03 \x01(\x0c\"D\n\x12\x44\x61taCreateResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\"\x91\x01\n\x0f\x44\x61taEditRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\x12\x17\n\nentry_name\x18\x03 \x01(\x0cH\x00\x88\x01\x01\x12\x17\n\nentry_data\x18\x04 \x01(\x0cH\x01\x88\x01\x01\x42\r\n\x0b_entry_nameB\r\n\x0b_entry_data\"B\n\x10\x44\x61taEditResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\"C\n\x11\x44\x61taDeleteRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\"D\n\x12\x44\x61taDeleteResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\"@\n\x0e\x44\x61taGetRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\"i\n\x0f\x44\x61taGetResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\x12\x12\n\nentry_name\x18\x03 \x01(\x0c\x12\x12\n\nentry_data\x18\x04 \x01(\x0c\"(\n\x0f\x44\x61taListRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\"Q\n\x10\x44\x61taListResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x12\n\nentry_name\x18\x02 \x03(\x0c\x12\x12\n\nentry_data\x18\x03 \x03(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.data.v0.data_payloads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATACREATEREQUEST']._serialized_start=64
  _globals['_DATACREATEREQUEST']._serialized_end=146
  _globals['_DATACREATERESPONSE']._serialized_start=148
  _globals['_DATACREATERESPONSE']._serialized_end=216
  _globals['_DATAEDITREQUEST']._serialized_start=219
  _globals['_DATAEDITREQUEST']._serialized_end=364
  _globals['_DATAEDITRESPONSE']._serialized_start=366
  _globals['_DATAEDITRESPONSE']._serialized_end=432
  _globals['_DATADELETEREQUEST']._serialized_start=434
  _globals['_DATADELETEREQUEST']._serialized_end=501
  _globals['_DATADELETERESPONSE']._serialized_start=503
  _globals['_DATADELETERESPONSE']._serialized_end=571
  _globals['_DATAGETREQUEST']._serialized_start=573
  _globals['_DATAGETREQUEST']._serialized_end=637
  _globals['_DATAGETRESPONSE']._serialized_start=639
  _globals['_DATAGETRESPONSE']._serialized_end=744
  _globals['_DATALISTREQUEST']._serialized_start=746
  _globals['_DATALISTREQUEST']._serialized_end=786
  _globals['_DATALISTRESPONSE']._serialized_start=788
  _globals['_DATALISTRESPONSE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
