# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from passmanager.common.v0 import error_pb2 as passmanager_dot_common_dot_v0_dot_error__pb2
from passmanager.common.v0 import secure_pb2 as passmanager_dot_common_dot_v0_dot_secure__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in passmanager/data/v0/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/passmanager.data.v0.Data/Create',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/passmanager.data.v0.Data/Edit',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/passmanager.data.v0.Data/Delete',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/passmanager.data.v0.Data/Get',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/passmanager.data.v0.Data/List',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/passmanager.data.v0.Data/Health',
                request_serializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.FromString,
                _registered_method=True)


class DataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'passmanager.data.v0.Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('passmanager.data.v0.Data', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.data.v0.Data/Create',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.data.v0.Data/Edit',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.data.v0.Data/Delete',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.data.v0.Data/Get',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.data.v0.Data/List',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.data.v0.Data/Health',
            passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.SerializeToString,
            passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
