"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DataCreateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_NAME_FIELD_NUMBER: _builtins.int
    ENTRY_DATA_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_name: _builtins.bytes
    entry_data: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_name: _builtins.bytes = ...,
        entry_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_data", b"entry_data", "entry_name", b"entry_name", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataCreateRequest: _TypeAlias = DataCreateRequest  # noqa: Y015

@_typing.final
class DataCreateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataCreateResponse: _TypeAlias = DataCreateResponse  # noqa: Y015

@_typing.final
class DataEditRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    ENTRY_NAME_FIELD_NUMBER: _builtins.int
    ENTRY_DATA_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    entry_name: _builtins.bytes
    entry_data: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
        entry_name: _builtins.bytes | None = ...,
        entry_data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_entry_data", b"_entry_data", "_entry_name", b"_entry_name", "entry_data", b"entry_data", "entry_name", b"entry_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_entry_data", b"_entry_data", "_entry_name", b"_entry_name", "entry_data", b"entry_data", "entry_name", b"entry_name", "entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__entry_data: _TypeAlias = _typing.Literal["entry_data"]  # noqa: Y015
    _WhichOneofArgType__entry_data: _TypeAlias = _typing.Literal["_entry_data", b"_entry_data"]  # noqa: Y015
    _WhichOneofReturnType__entry_name: _TypeAlias = _typing.Literal["entry_name"]  # noqa: Y015
    _WhichOneofArgType__entry_name: _TypeAlias = _typing.Literal["_entry_name", b"_entry_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__entry_data) -> _WhichOneofReturnType__entry_data | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__entry_name) -> _WhichOneofReturnType__entry_name | None: ...

Global___DataEditRequest: _TypeAlias = DataEditRequest  # noqa: Y015

@_typing.final
class DataEditResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataEditResponse: _TypeAlias = DataEditResponse  # noqa: Y015

@_typing.final
class DataDeleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataDeleteRequest: _TypeAlias = DataDeleteRequest  # noqa: Y015

@_typing.final
class DataDeleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataDeleteResponse: _TypeAlias = DataDeleteResponse  # noqa: Y015

@_typing.final
class DataGetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataGetRequest: _TypeAlias = DataGetRequest  # noqa: Y015

@_typing.final
class DataGetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    ENTRY_NAME_FIELD_NUMBER: _builtins.int
    ENTRY_DATA_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    entry_name: _builtins.bytes
    entry_data: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
        entry_name: _builtins.bytes = ...,
        entry_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_data", b"entry_data", "entry_name", b"entry_name", "entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataGetResponse: _TypeAlias = DataGetResponse  # noqa: Y015

@_typing.final
class DataListRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataListRequest: _TypeAlias = DataListRequest  # noqa: Y015

@_typing.final
class DataListResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_NAME_FIELD_NUMBER: _builtins.int
    ENTRY_DATA_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    @_builtins.property
    def entry_name(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def entry_data(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_name: _abc.Iterable[_builtins.bytes] | None = ...,
        entry_data: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_data", b"entry_data", "entry_name", b"entry_name", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DataListResponse: _TypeAlias = DataListResponse  # noqa: Y015
