# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/password/v0/password_payloads.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/password/v0/password_payloads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/passmanager/password/v0/password_payloads.proto\x12\x17passmanager.password.v0\"n\n\x14PasswordStartRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x10\n\x08srp_salt\x18\x02 \x01(\x0c\x12\x14\n\x0csrp_verifier\x18\x03 \x01(\x0c\x12\x17\n\x0fmaster_key_salt\x18\x04 \x01(\x0c\"g\n\x15PasswordStartResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61uth_id\x18\x02 \x01(\t\x12\x10\n\x08srp_salt\x18\x03 \x01(\x0c\x12\x14\n\x0c\x65ph_public_b\x18\x04 \x01(\x0c\"f\n\x13PasswordAuthRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61uth_id\x18\x02 \x01(\t\x12\x11\n\teph_val_a\x18\x03 \x01(\x0c\x12\x14\n\x0cproof_val_m1\x18\x04 \x01(\x0c\"m\n\x14PasswordAuthResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x17\n\x0fserver_proof_m2\x18\x03 \x01(\x0c\x12\x11\n\tentry_ids\x18\x04 \x03(\t\"0\n\x17PasswordCompleteRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\"1\n\x18PasswordCompleteResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\"-\n\x14PasswordAbortRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\".\n\x15PasswordAbortResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\"D\n\x12PasswordGetRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\"m\n\x13PasswordGetResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\x12\x12\n\nentry_name\x18\x03 \x01(\x0c\x12\x12\n\nentry_data\x18\x04 \x01(\x0c\"o\n\x15PasswordUpdateRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\t\x12\x12\n\nentry_name\x18\x03 \x01(\x0c\x12\x12\n\nentry_data\x18\x04 \x01(\x0c\"H\n\x16PasswordUpdateResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x17\n\x0f\x65ntry_public_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.password.v0.password_payloads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSWORDSTARTREQUEST']._serialized_start=76
  _globals['_PASSWORDSTARTREQUEST']._serialized_end=186
  _globals['_PASSWORDSTARTRESPONSE']._serialized_start=188
  _globals['_PASSWORDSTARTRESPONSE']._serialized_end=291
  _globals['_PASSWORDAUTHREQUEST']._serialized_start=293
  _globals['_PASSWORDAUTHREQUEST']._serialized_end=395
  _globals['_PASSWORDAUTHRESPONSE']._serialized_start=397
  _globals['_PASSWORDAUTHRESPONSE']._serialized_end=506
  _globals['_PASSWORDCOMPLETEREQUEST']._serialized_start=508
  _globals['_PASSWORDCOMPLETEREQUEST']._serialized_end=556
  _globals['_PASSWORDCOMPLETERESPONSE']._serialized_start=558
  _globals['_PASSWORDCOMPLETERESPONSE']._serialized_end=607
  _globals['_PASSWORDABORTREQUEST']._serialized_start=609
  _globals['_PASSWORDABORTREQUEST']._serialized_end=654
  _globals['_PASSWORDABORTRESPONSE']._serialized_start=656
  _globals['_PASSWORDABORTRESPONSE']._serialized_end=702
  _globals['_PASSWORDGETREQUEST']._serialized_start=704
  _globals['_PASSWORDGETREQUEST']._serialized_end=772
  _globals['_PASSWORDGETRESPONSE']._serialized_start=774
  _globals['_PASSWORDGETRESPONSE']._serialized_end=883
  _globals['_PASSWORDUPDATEREQUEST']._serialized_start=885
  _globals['_PASSWORDUPDATEREQUEST']._serialized_end=996
  _globals['_PASSWORDUPDATERESPONSE']._serialized_start=998
  _globals['_PASSWORDUPDATERESPONSE']._serialized_end=1070
# @@protoc_insertion_point(module_scope)
