# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from passmanager.common.v0 import error_pb2 as passmanager_dot_common_dot_v0_dot_error__pb2
from passmanager.common.v0 import secure_pb2 as passmanager_dot_common_dot_v0_dot_secure__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in passmanager/password/v0/password_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PasswordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/passmanager.password.v0.Password/Start',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Auth = channel.unary_unary(
                '/passmanager.password.v0.Password/Auth',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/passmanager.password.v0.Password/Complete',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/passmanager.password.v0.Password/Abort',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/passmanager.password.v0.Password/Get',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/passmanager.password.v0.Password/Update',
                request_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/passmanager.password.v0.Password/Health',
                request_serializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.SerializeToString,
                response_deserializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.FromString,
                _registered_method=True)


class PasswordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Auth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PasswordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Auth': grpc.unary_unary_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.FromString,
                    response_serializer=passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'passmanager.password.v0.Password', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('passmanager.password.v0.Password', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Password(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Start',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Auth',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Complete',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Abort',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Get',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Update',
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureRequest.SerializeToString,
            passmanager_dot_common_dot_v0_dot_secure__pb2.SecureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/passmanager.password.v0.Password/Health',
            passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.SerializeToString,
            passmanager_dot_common_dot_v0_dot_error__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
