"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PasswordStartRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    SRP_SALT_FIELD_NUMBER: _builtins.int
    SRP_VERIFIER_FIELD_NUMBER: _builtins.int
    MASTER_KEY_SALT_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    srp_salt: _builtins.bytes
    srp_verifier: _builtins.bytes
    master_key_salt: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        srp_salt: _builtins.bytes = ...,
        srp_verifier: _builtins.bytes = ...,
        master_key_salt: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["master_key_salt", b"master_key_salt", "srp_salt", b"srp_salt", "srp_verifier", b"srp_verifier", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordStartRequest: _TypeAlias = PasswordStartRequest  # noqa: Y015

@_typing.final
class PasswordStartResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    AUTH_ID_FIELD_NUMBER: _builtins.int
    SRP_SALT_FIELD_NUMBER: _builtins.int
    EPH_PUBLIC_B_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    auth_id: _builtins.str
    srp_salt: _builtins.bytes
    eph_public_b: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        auth_id: _builtins.str = ...,
        srp_salt: _builtins.bytes = ...,
        eph_public_b: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_id", b"auth_id", "eph_public_b", b"eph_public_b", "srp_salt", b"srp_salt", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordStartResponse: _TypeAlias = PasswordStartResponse  # noqa: Y015

@_typing.final
class PasswordAuthRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    AUTH_ID_FIELD_NUMBER: _builtins.int
    EPH_VAL_A_FIELD_NUMBER: _builtins.int
    PROOF_VAL_M1_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    auth_id: _builtins.str
    eph_val_a: _builtins.bytes
    proof_val_m1: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        auth_id: _builtins.str = ...,
        eph_val_a: _builtins.bytes = ...,
        proof_val_m1: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_id", b"auth_id", "eph_val_a", b"eph_val_a", "proof_val_m1", b"proof_val_m1", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordAuthRequest: _TypeAlias = PasswordAuthRequest  # noqa: Y015

@_typing.final
class PasswordAuthResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    SERVER_PROOF_M2_FIELD_NUMBER: _builtins.int
    ENTRY_IDS_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    session_id: _builtins.str
    server_proof_m2: _builtins.bytes
    @_builtins.property
    def entry_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        session_id: _builtins.str = ...,
        server_proof_m2: _builtins.bytes = ...,
        entry_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_ids", b"entry_ids", "server_proof_m2", b"server_proof_m2", "session_id", b"session_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordAuthResponse: _TypeAlias = PasswordAuthResponse  # noqa: Y015

@_typing.final
class PasswordCompleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordCompleteRequest: _TypeAlias = PasswordCompleteRequest  # noqa: Y015

@_typing.final
class PasswordCompleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordCompleteResponse: _TypeAlias = PasswordCompleteResponse  # noqa: Y015

@_typing.final
class PasswordAbortRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordAbortRequest: _TypeAlias = PasswordAbortRequest  # noqa: Y015

@_typing.final
class PasswordAbortResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordAbortResponse: _TypeAlias = PasswordAbortResponse  # noqa: Y015

@_typing.final
class PasswordGetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordGetRequest: _TypeAlias = PasswordGetRequest  # noqa: Y015

@_typing.final
class PasswordGetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    ENTRY_NAME_FIELD_NUMBER: _builtins.int
    ENTRY_DATA_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    entry_name: _builtins.bytes
    entry_data: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
        entry_name: _builtins.bytes = ...,
        entry_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_data", b"entry_data", "entry_name", b"entry_name", "entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordGetResponse: _TypeAlias = PasswordGetResponse  # noqa: Y015

@_typing.final
class PasswordUpdateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    ENTRY_NAME_FIELD_NUMBER: _builtins.int
    ENTRY_DATA_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    entry_name: _builtins.bytes
    entry_data: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
        entry_name: _builtins.bytes = ...,
        entry_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_data", b"entry_data", "entry_name", b"entry_name", "entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordUpdateRequest: _TypeAlias = PasswordUpdateRequest  # noqa: Y015

@_typing.final
class PasswordUpdateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    ENTRY_PUBLIC_ID_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    entry_public_id: _builtins.str
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        entry_public_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry_public_id", b"entry_public_id", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PasswordUpdateResponse: _TypeAlias = PasswordUpdateResponse  # noqa: Y015
