# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/password/v0/password.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/password/v0/password.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from passmanager.common.v0 import error_pb2 as passmanager_dot_common_dot_v0_dot_error__pb2
from passmanager.common.v0 import secure_pb2 as passmanager_dot_common_dot_v0_dot_secure__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&passmanager/password/v0/password.proto\x12\x17passmanager.password.v0\x1a!passmanager/common/v0/error.proto\x1a\"passmanager/common/v0/secure.proto2\xe7\x04\n\x08Password\x12T\n\x05Start\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12S\n\x04\x41uth\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12W\n\x08\x43omplete\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12T\n\x05\x41\x62ort\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12R\n\x03Get\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12U\n\x06Update\x12$.passmanager.common.v0.SecureRequest\x1a%.passmanager.common.v0.SecureResponse\x12V\n\x06Health\x12%.passmanager.common.v0.HealthResponse\x1a%.passmanager.common.v0.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.password.v0.password_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSWORD']._serialized_start=139
  _globals['_PASSWORD']._serialized_end=754
# @@protoc_insertion_point(module_scope)
