# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passmanager/user/v0/user_payloads.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'passmanager/user/v0/user_payloads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'passmanager/user/v0/user_payloads.proto\x12\x13passmanager.user.v0\"B\n\x13UserUsernameRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x12\x14\n\x0cnew_username\x18\x02 \x01(\x0c\",\n\x14UserUsernameResponse\x12\x14\n\x0cnew_username\x18\x01 \x01(\x0c\"*\n\x11UserDeleteRequest\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\"+\n\x12UserDeleteResponse\x12\x15\n\rusername_hash\x18\x01 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passmanager.user.v0.user_payloads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERUSERNAMEREQUEST']._serialized_start=64
  _globals['_USERUSERNAMEREQUEST']._serialized_end=130
  _globals['_USERUSERNAMERESPONSE']._serialized_start=132
  _globals['_USERUSERNAMERESPONSE']._serialized_end=176
  _globals['_USERDELETEREQUEST']._serialized_start=178
  _globals['_USERDELETEREQUEST']._serialized_end=220
  _globals['_USERDELETERESPONSE']._serialized_start=222
  _globals['_USERDELETERESPONSE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
