"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserUsernameRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    NEW_USERNAME_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    new_username: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
        new_username: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_username", b"new_username", "username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserUsernameRequest: _TypeAlias = UserUsernameRequest  # noqa: Y015

@_typing.final
class UserUsernameResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NEW_USERNAME_FIELD_NUMBER: _builtins.int
    new_username: _builtins.bytes
    def __init__(
        self,
        *,
        new_username: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["new_username", b"new_username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserUsernameResponse: _TypeAlias = UserUsernameResponse  # noqa: Y015

@_typing.final
class UserDeleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserDeleteRequest: _TypeAlias = UserDeleteRequest  # noqa: Y015

@_typing.final
class UserDeleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_HASH_FIELD_NUMBER: _builtins.int
    username_hash: _builtins.bytes
    def __init__(
        self,
        *,
        username_hash: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserDeleteResponse: _TypeAlias = UserDeleteResponse  # noqa: Y015
