"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from passmanager.common.v0 import error_pb2 as _error_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserRegisterRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NEW_USERNAME_FIELD_NUMBER: _builtins.int
    SRP_SALT_FIELD_NUMBER: _builtins.int
    SRP_VERIFIER_FIELD_NUMBER: _builtins.int
    MASTER_KEY_SALT_FIELD_NUMBER: _builtins.int
    new_username: _builtins.bytes
    srp_salt: _builtins.bytes
    srp_verifier: _builtins.bytes
    master_key_salt: _builtins.bytes
    def __init__(
        self,
        *,
        new_username: _builtins.bytes = ...,
        srp_salt: _builtins.bytes = ...,
        srp_verifier: _builtins.bytes = ...,
        master_key_salt: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["master_key_salt", b"master_key_salt", "new_username", b"new_username", "srp_salt", b"srp_salt", "srp_verifier", b"srp_verifier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserRegisterRequest: _TypeAlias = UserRegisterRequest  # noqa: Y015

@_typing.final
class UserRegisterResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Success(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        USERNAME_HASH_FIELD_NUMBER: _builtins.int
        username_hash: _builtins.bytes
        def __init__(
            self,
            *,
            username_hash: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["username_hash", b"username_hash"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SUCCESS_FIELD_NUMBER: _builtins.int
    SUCCESS_DATA_FIELD_NUMBER: _builtins.int
    FAILURE_DATA_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def success_data(self) -> Global___UserRegisterResponse.Success: ...
    @_builtins.property
    def failure_data(self) -> _error_pb2.Failure: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        success_data: Global___UserRegisterResponse.Success | None = ...,
        failure_data: _error_pb2.Failure | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success_data", b"success_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure_data", b"failure_data", "result", b"result", "success", b"success", "success_data", b"success_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["success_data", "failure_data"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___UserRegisterResponse: _TypeAlias = UserRegisterResponse  # noqa: Y015
